#!/usr/bin/env bash
# gives information about a file name 'school'

file="school"
if [ -e $file ]; then
    echo "$file file exist"
else
    echo "$file does not exist"
    exit
fi

if [ -s $file ]; then
    echo "$file is not empty"
else
    echo "$file file is empty"
fi

if [ -f $file ]; then
    echo "$file is a regular file"
else
    exit
fi