#!/usr/bin/env bash
# gives information about a file name 'school'

file="school"
if [ -e $file ]; then
    echo "school file exist"
else
    echo "school does not exist"
    exit 1
fi

if [ -s $file ]; then
    echo "school is not empty"
else
    echo "school file is empty"
fi

if [ -f $file ]; then
    echo "school is a regular file"
fi