#!/usr/bin/env bash
# Overwrites the systems hosts file

cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2\tlocalhost" > ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
