#!/usr/bin/env bash
# Runs the whoami command under the user passed as argument.

# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

sudo -u "$1" whoami
